# Genetic Algorithm Parameters
ga_settings:
  population_size: 50
  generations: 100
  mutation_rate: 0.1
  crossover_rate: 0.8
  elitism_count: 5

# Vehicle Settings
vehicle_types:
  small:
    capacity: 2.0
    cost_per_km: 1
    speed: 40
  medium:
    capacity: 5.0
    cost_per_km: 2
    speed: 40
  large:
    capacity: 10.0
    cost_per_km: 3
    speed: 40

# Agent Communication Settings
agent_settings:
  message_timeout: 5000
  retry_attempts: 3
  protocol: 'fipa-contract-net'

# GUI Settings
gui_settings:
  window_size: [1200, 800]
  map_size: [800, 600]
  refresh_rate: 1000
